version: '2'

services:
  php:
    build: ./docker/php
    volumes:
      - ./www-root:/var/www/html
      - /var/log/apache2/blog:/var/log/apache2/
    ports:
      - '8000:80'
    environment:
      - VIRTUAL_HOST=php.localhost
    depends_on:
      - db

  db:
    build: ./docker/mysql